name: SMP_Reboot
version: '${project.version}'
main: de.jinx.smp_reborn.SMP_Reboot
api-version: 1.19

commands:
  broadcast:
  rename:
  testString:
  luckwheel:
  createWizard:
  customItems:
  souls:
  printInfo: